name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      issues: write    # For manual-approval
      contents: write  # For pushing snapshot updates
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        id: run-tests
        continue-on-error: true
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Wait for snapshot update approval
        if: steps.run-tests.outcome == 'failure'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Playwright Snapshot Update Required"
          issue-body: "Playwright tests failed. Would you like to update the snapshots?"

      - name: Update snapshots
        if: steps.run-tests.outcome == 'failure'
        run: |
          npx playwright test --update-snapshots
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "test: update playwright snapshots" || echo "No changes to commit"
          git push
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
